services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: railflow-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: railflow-rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  
  notificationservice:
    build:
      context: .
      dockerfile: src/RailFlow.NotificationService/Dockerfile
    restart: unless-stopped
    environment:
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__User: guest
      RabbitMQ__Password: guest
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  sql_data:
